### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by crader-dev** [mickeyh11/Home-Automation#23]
- [x] Architecture Diagram
- [x] Architecture Explanation

Pick one (or multiple) architectural style(s) that best fit(s) your project. Draw an architecture diagram for your project that follows your selected style(s). In your diagram, the component names should be specific to your project (instead of their names in the architectural style).

Write a brief text explaining how the components of your architecture diagram correspond to those defined in the architectural style that they follow. 

It is ok to mix multiple architectural styles for your project. Make sure to mention which architectural style(s) you chose. If you are mixing multiple architectural styles, make sure you mention which parts of your architecture follow which styles.

The terminology used in this diagram should also be consistent with the one used in your requirements analysis.

**Comment by mickeyh11** [comment]
Talking points for meeting:
**Event-Based Architecture**
- Promotes the production, detection, consumption of, and reaction to events
- Event-driven programming
- Lends itself to mobile applications, due to non-deterministic nature of control flow
- Anonymous handlers of events
- Support reuse and evolution, new consumers easy to add

**Layered/Tiered Architecture**(Probably 2-layer or Client-Server??)
- _Client_ {Presentation}: UI to interact with users (Mobile App)
- _Server_ {Logic (communication with devices) and Data (users and privileges)}: communication link between user and devices and user information (HUB)
